# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-22 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20161119_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='age',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='patient',
            name='address',
            field=models.CharField(default='', max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medication',
            name='date_prescribed',
            field=models.DateField(default='2016-11-16'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='dob',
            field=models.DateField(default='1984-01-01'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='date',
            field=models.DateField(default='2016-11-16'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='date',
            field=models.DateField(verbose_name='2016-11-16'),
        ),
    ]
